version: "3.7"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=imdbcrawler
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  crawler-beemon:
    build: .
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=imdbcrawler
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
      - DATABASE_PORT=5432
    depends_on:
      - postgres
volumes:
  pgdata: